### ISSUE TITLE
[Frontend] Implementation of user registration

### ISSUE THREAD

**Issue by nathanaelg16** [Devature/penguin-client#4]
As a user, I should be able to sign up for an account with Ticket Penguin. 

- The registration process should collect user details such as full name, username, password, role, and email address, and be persisted to the database via an API call to the backend server at `/users/registration`.
-  The registration process should handle any errors received from the backend, such as duplicated email, non-unique username, and password security constraints.

**Comment by soot0-JoshR** [comment]
This issue has been resolved and the user story satisfied.
