### ISSUE TITLE
[Frontend] User login

### ISSUE THREAD

**Issue by nathanaelg16** [Devature/penguin-client#5]
As a user, I should be able to login to my Ticket Penguin account after registering.

- The login form should collect a user's username and password, and perform an HTTP POST request to the backend server at `/users/login` to verify the credentials.
- The frontend should handle any errors resulting from the login request, such as HTTP 401 Unauthorized.
- If the login succeeds, the frontend should save the received JWT token and store it in the session storage for subsequent requests, and redirect the user to the home page.

**Comment by soot0-JoshR** [comment]
This issue has been resolved and the user story completed.
